### PR TITLE
Upload signature functionality added

### PR DESCRIPTION
**Pull request by amohapatra123**
#22

### CODE REVIEW

**Comment by amohapatra123** [comment]
please review my PR. @irsayvid

**Comment by irsayvid** [comment]
Can you please add the screenshots of how it looks after adding this functionality. I have a doubt whether it works or not because imagettftext function is used only for text. File data is sent to php file using `var fd = new FormData();
        var files = $('#fileinputid')[0].files[0];
        fd.append('file', files);`  something like this. 
Attached screenshots of home page and the redirected certificate would work.

**Comment by amohapatra123** [comment]
some points to consider:
1.All the templates are not one alike some have signature and some do not.
2.It is not a good idea to overlay one image over other image

hence what i have made a change is just added a input box so that we can take input of the name for the signature and append it to the template image.
screencapture-localhost-Project-celadon-certificates-Anshuman-Mohapatra-HACTOBERFEST-2020-2020-10-30-jpg-2020-10-10-16_04_12

**Comment by irsayvid** [comment]
This is just initial one. We'll  change the conditions later based on different templates. It would be great if you can add file upload for signature because text doesn't look good for signature. (image on image would work like pdf on pdf in case of Adobe acrobat)

**Comment by amohapatra123** [comment]
ok i will do but if you can lable this PR as hactoberfest-accepted

**Pull request closed without merging**
